package work.koreyoshi.file.project.common.model;

import work.koreyoshi.file.project.common.model.base.BaseFileStorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileStorage extends BaseFileStorage<FileStorage> {
	
}
