package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseMqIdempotentConsumeMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqIdempotentConsumeMessage extends BaseMqIdempotentConsumeMessage<MqIdempotentConsumeMessage> {
	
}
