package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseMqMandatoryMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqMandatoryMessage extends BaseMqMandatoryMessage<MqMandatoryMessage> {
	
}
