package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseSysAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccount extends BaseSysAccount<SysAccount> {
	
}
