package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseSysAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccountRole extends BaseSysAccountRole<SysAccountRole> {
	
}
