package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseSysPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPermission extends BaseSysPermission<SysPermission> {
	
}
