package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseSysRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRolePermission extends BaseSysRolePermission<SysRolePermission> {
	
}
