package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	
}
