package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	
}
