package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountRole extends BaseAccountRole<AccountRole> {
	
}
