package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	
}
