package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	
}
