package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	
}
