package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Token extends BaseToken<Token> {
	
}
