package work.koreyoshi.project.common.model;

import work.koreyoshi.project.common.model.base.BaseVideos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Videos extends BaseVideos<Videos> {
	
}
