package work.koreyoshi.project.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

	public void setPermissionId(java.lang.String permissionId) {
		set("permission_id", permissionId);
	}
	
	public java.lang.String getPermissionId() {
		return getStr("permission_id");
	}

	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.String getRoleId() {
		return getStr("role_id");
	}

}
