package work.koreyoshi.project.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVideos<M extends BaseVideos<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSubscribe(java.lang.Boolean subscribe) {
		set("subscribe", subscribe);
	}
	
	public java.lang.Boolean getSubscribe() {
		return get("subscribe");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setCurrent(java.lang.Integer current) {
		set("current", current);
	}
	
	public java.lang.Integer getCurrent() {
		return getInt("current");
	}

	public void setBelongTo(java.lang.String belongTo) {
		set("belong_to", belongTo);
	}
	
	public java.lang.String getBelongTo() {
		return getStr("belong_to");
	}

	public void setTos(java.lang.String tos) {
		set("tos", tos);
	}
	
	public java.lang.String getTos() {
		return getStr("tos");
	}

}
