package work.koreyoshi.project.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountRole<M extends BaseAccountRole<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.String getRoleId() {
		return getStr("role_id");
	}

	public void setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
	}
	
	public java.lang.String getAccountId() {
		return getStr("account_id");
	}

}
