package work.koreyoshi.project.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMqMandatoryMessage<M extends BaseMqMandatoryMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMessageId(java.lang.String messageId) {
		set("message_id", messageId);
	}
	
	public java.lang.String getMessageId() {
		return getStr("message_id");
	}

	public void setQueue(java.lang.String queue) {
		set("queue", queue);
	}
	
	public java.lang.String getQueue() {
		return getStr("queue");
	}

	public void setMessageBody(java.lang.String messageBody) {
		set("message_body", messageBody);
	}
	
	public java.lang.String getMessageBody() {
		return getStr("message_body");
	}

	public void setListener(java.lang.String listener) {
		set("listener", listener);
	}
	
	public java.lang.String getListener() {
		return getStr("listener");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
