package work.koreyoshi.project.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMqIdempotentConsumeMessage<M extends BaseMqIdempotentConsumeMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMessageId(java.lang.String messageId) {
		set("message_id", messageId);
	}
	
	public java.lang.String getMessageId() {
		return getStr("message_id");
	}

	public void setQueue(java.lang.String queue) {
		set("queue", queue);
	}
	
	public java.lang.String getQueue() {
		return getStr("queue");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
